.TH "adicionar.cpp" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adicionar.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'adicionar\&.h'\fP
.br
\fC#include 'ui_adicionar\&.h'\fP
.br
\fC#include 'conexao\&.h'\fP
.br
\fC#include <QRegExp>\fP
.br
\fC#include <QMessageBox>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
