.TH "Adicionar" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Adicionar \- 
.PP
Classe \fBAdicionar\fP\&. Interface Gráfica responsável por adicionar novos funcionários no projeto\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <adicionar\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdicionar\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Adicionar\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classe \fBAdicionar\fP\&. Interface Gráfica responsável por adicionar novos funcionários no projeto\&. 

A Classe \fBAdicionar\fP consiste em uma QDialog e possui os dados principais de um funcionário, que serão colocados no Banco de Dados employees, além disso, inclui no Banco user um usuário e senha para se logar no sistema, sendo este segundo composto de login: (primeiro nome da pessoa) e senha: cpf da pessoa\&. 
.PP
Definition at line 18 of file adicionar\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Adicionar::Adicionar (QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 10 of file adicionar\&.cpp\&.
.SS "Adicionar::~Adicionar ()"

.PP
Definition at line 18 of file adicionar\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
