.TH "Alterar" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alterar \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <alterar\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlterar\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Alterar\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file alterar\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Alterar::Alterar (QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 9 of file alterar\&.cpp\&.
.SS "Alterar::~Alterar ()"

.PP
Definition at line 23 of file alterar\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
