.TH "Cadastrar" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cadastrar \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cadastrar\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCadastrar\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Cadastrar\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QStringList \fBfuncionarios\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file cadastrar\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Cadastrar::Cadastrar (QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 11 of file cadastrar\&.cpp\&.
.SS "Cadastrar::~Cadastrar ()"

.PP
Definition at line 61 of file cadastrar\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QStringList Cadastrar::funcionarios"

.PP
Definition at line 25 of file cadastrar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
