.TH "Caixa" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Caixa \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <caixa\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCaixa\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Caixa\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file caixa\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Caixa::Caixa (QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 17 of file caixa\&.cpp\&.
.SS "Caixa::~Caixa ()"

.PP
Definition at line 29 of file caixa\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
