.TH "conexao.cpp" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conexao.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'conexao\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <ctime>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBhostname\fP   'localhost'"
.br
.ti -1c
.RI "#define \fBusername\fP   'root'"
.br
.ti -1c
.RI "#define \fBpassword\fP   '2701'"
.br
.ti -1c
.RI "#define \fBdbname\fP   'Estoque'"
.br
.ti -1c
.RI "#define \fBsocketname\fP   NULL"
.br
.ti -1c
.RI "#define \fBportnumber\fP   1563"
.br
.ti -1c
.RI "#define \fBflags\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define dbname   'Estoque'"

.PP
Definition at line 15 of file conexao\&.cpp\&.
.SS "#define flags   0"

.PP
Definition at line 18 of file conexao\&.cpp\&.
.SS "#define hostname   'localhost'"

.PP
Definition at line 12 of file conexao\&.cpp\&.
.SS "#define password   '2701'"

.PP
Definition at line 14 of file conexao\&.cpp\&.
.SS "#define portnumber   1563"

.PP
Definition at line 17 of file conexao\&.cpp\&.
.SS "#define socketname   NULL"

.PP
Definition at line 16 of file conexao\&.cpp\&.
.SS "#define username   'root'"

.PP
Definition at line 13 of file conexao\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
