.TH "conexao.h" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conexao.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <clocale>\fP
.br
\fC#include <mysql/mysql\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConexao\fP"
.br
.RI "\fIClasse Conexão\&. Classe C++ que inclui bibliotecas do Qt, C++ e MySQL para realizar a conexão entre Interface Gráfica, C++ e Banco de Dados\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
