.TH "Delete" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Delete \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <delete\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDelete\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Delete\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file delete\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Delete::Delete (QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 9 of file delete\&.cpp\&.
.SS "Delete::~Delete ()"

.PP
Definition at line 16 of file delete\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
