.TH "Financas" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Financas \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <financas\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFinancas\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Financas\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBemployeePayment\fP"
.br
.ti -1c
.RI "double \fBproductExpenses\fP"
.br
.ti -1c
.RI "double \fBtotal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file financas\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Financas::Financas (QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 13 of file financas\&.cpp\&.
.SS "Financas::~Financas ()"

.PP
Definition at line 78 of file financas\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double Financas::employeePayment"

.PP
Definition at line 14 of file financas\&.h\&.
.SS "double Financas::productExpenses"

.PP
Definition at line 15 of file financas\&.h\&.
.SS "double Financas::total"

.PP
Definition at line 16 of file financas\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
