.TH "gerente.cpp" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gerente.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'gerente\&.h'\fP
.br
\fC#include 'ui_gerente\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
