.TH "Gerente" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gerente \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gerente\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGerente\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Gerente\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCaixa\fP \fBcaixa\fP"
.br
.ti -1c
.RI "\fBCadastrar\fP \fBfuncionario\fP"
.br
.ti -1c
.RI "\fBProdutos\fP \fBprodutos\fP"
.br
.ti -1c
.RI "\fBFinancas\fP \fBbalanco\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file gerente\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Gerente::Gerente (QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 5 of file gerente\&.cpp\&.
.SS "Gerente::~Gerente ()"

.PP
Definition at line 15 of file gerente\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFinancas\fP Gerente::balanco"

.PP
Definition at line 23 of file gerente\&.h\&.
.SS "\fBCaixa\fP Gerente::caixa"

.PP
Definition at line 20 of file gerente\&.h\&.
.SS "\fBCadastrar\fP Gerente::funcionario"

.PP
Definition at line 21 of file gerente\&.h\&.
.SS "\fBProdutos\fP Gerente::produtos"

.PP
Definition at line 22 of file gerente\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
