.TH "mainwindow.h" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include 'caixa\&.h'\fP
.br
\fC#include 'gerente\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
