.TH "produtos.cpp" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
produtos.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'produtos\&.h'\fP
.br
\fC#include 'ui_produtos\&.h'\fP
.br
\fC#include 'conexao\&.h'\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QStandardItem>\fP
.br
\fC#include <QStandardItemModel>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
