.TH "Produtos" 3 "Fri Dec 4 2015" "Sistema de Controle e Estoque de Produção" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Produtos \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <produtos\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProdutos\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Produtos\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file produtos\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Produtos::Produtos (QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 12 of file produtos\&.cpp\&.
.SS "Produtos::~Produtos ()"

.PP
Definition at line 51 of file produtos\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Controle e Estoque de Produção from the source code\&.
